# PYTHON NO VIENE CON MUCHOS METODOS ESTABLECIDOS DE FORMA PREDETERMINADA ASI QUE HAY MODULOS QUE SE INTEGRAN EN UN ARCHIVO PARA PORDER TARBAJAR CON EXTRA METODOS O FUNCIONES Y DE ESA MANERA PODER TRABAJAR MEJOR CON NUMEROS.

# EN SI MATH SE LLAMA MATH.PY QUE ES UN ARCHIVO CON CODIGO ESCRITO EN PYTHON
import math

# ESTE METODO DE LA IMPORTACION O EN SI DEL MODULO VA LLEVAR NUESTRO NUMERO AL SIGUIENTE ENTERO MAS CERCANO
print(math.ceil(1))
print(math.ceil(1.1))
print(" ")

# ESTE METODO DEL MODULO MATH VA RETOMAR EL NUMERO INDEPENDIENTE Y LO VA A LLEVAR AL NUMERO ENTERO MAS CERCANO PERO ANTERIOR
print(math.floor(1))
print(math.floor(1.99999999))
print(" ")

# EL SIGUIENTE METODO DEL MODULO MATH ANALIZA EL VALOR Y TE DICE DE FORMA BOLLEANO CORRESPONDE A QUE NO ES NUMEOR EN ESTE CASO TE VA DAR FALSE PUES SI ES UN NUMERO PERO SI NO LO ES TE MARCA UN TRACEBACK DICIENDO QUE NO ES UN NUMERO SERIA COMO SU FORMA DE DECIR TRUE NO ES UN NUMERO
print(math.isnan(23))
print(" ")

# EL SIGUIENTE METODDO DEL MODULO MATH REALIZA UN POTENCIA EL PRIMER VALOR ES EL NUMERO Y EL SEGUNDO LA POTENCIA
print(math.pow(10, 3))
print(" ")

# EL SIGUIENTE METODO DEL MODULO MATH ANALIZA TU VALOR Y TE DICE TRAS UNA RAIZ CUADRADA EL RESULTADO (ES PARA SACAR RAIZ CUADRADA)
print(math.sqrt(9))
print(" ")

# ENTONCES ES NECESARIO CONSULTAR DOCUMMENTACION DE LIBRERIA MATH O EN PYTHON CONOCIDO COMO MODULO PARA VER TODOS LOS METODOS POSIBLES.   LINK:    https://docs.python.org/3/library/math.html

print("https://docs.python.org/3/library/math.html")