# LOS OPERADORES DE COMPARACION O LOS COMPARADORES SON LOS SIGUIENTES

# ALGO MAS ES QUE UNA EXPRESION ES UNA CADENA DE INSTRUCCIONES QUE despues VAN EVALUAR en UNA UNICA COSA

# LOS COMPARADORES VAN SIEMPRE A DEVOLVER YA SEA TRUE O YA SEA FALSE
print(1 > 2)
print(1 < 2)
print(2 >= 2)
print(2 <= 2)
print(2 == 2)
print(1 == 2)
print(1 == "2")
print(2 != "2")
print(2 != 2)
print(1 != 2)


# GENERALMENTE MEJOR LLAMALES COMPARADORES LOGICOS
